version: "3.8"
services:
  test-database:
    image: mysql_image:latest
    container_name: ${AUTH_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${AUTH_DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${AUTH_DATABASE_NAME}
      - MYSQL_USER=${AUTH_DATABASE_USER}
      - MYSQL_PASSWORD=${AUTH_DATABASE_PASSWORD}