version: '3.8'

services:
  product-management-service:
    image: offbrand_product-management-service:latest
    container_name: product-management-service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - product-management-service-db
    networks:
      - product-management-service-network

  product-management-service-db:
    image: mysql:8.0
    container_name: product-management-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
    networks:
      - product-management-service-network
  
  product-managment-service-prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: product-managment-service-db
            port: 3306
            user: root
            password: mysecretpassword

networks:
  product-management-service-network: