version: "3.8"
services:
  ums-production-database:
    image: mysql_image:latest
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    networks:
      - ums_production_network
    volumes:
      - ums_mysql_data:/var/lib/mysql
    
  ums-production-app:
    image: ums_prod_app:latest
    container_name: ${APP_CONTAINER_NAME}
    restart: no
    entrypoint: ["sh", "-c", "while ! npm run start:migrate:prod; do echo 'The database is not ready yet! Retrying after a delay...'; sleep ${DATABASE_CONN_RETRY_DELAY:- 2}; done"]
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - ums-production-database
    env_file:
      - .env
    networks:
      - ums_production_network
    
volumes:
  ums_mysql_data:
    driver: local

networks:
  ums_production_network:
