version: "3.8"
services:
  test-database:
    image: mysql_image:latest
    container_name: ${UMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${UMS_DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${UMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${UMS_DATABASE_NAME}
      - MYSQL_USER=${UMS_DATABASE_USER}
      - MYSQL_PASSWORD=${UMS_DATABASE_PASSWORD}