version: "3.8"
services:
  ums-production-database:
    image: mysql_image:latest
    container_name: ${UMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${UMS_DATABASE_PORT}:${UMS_DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${UMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${UMS_DATABASE_NAME}
      - MYSQL_USER=${UMS_DATABASE_USER}
      - MYSQL_PASSWORD=${UMS_DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${UMS_DATABASE_PORT}
    networks:
      - ums_production_network
    volumes:
      - ums_mysql_data_isolated:/var/lib/mysql
    
  ums-production-app:
    image: ums_prod_app:latest
    container_name: ${UMS_APP_CONTAINER_NAME}
    restart: no
    entrypoint: ["sh", "-c", "while ! npm run start:migrate:prod; do echo 'The database is not ready yet! Retrying after a delay...'; sleep ${UMS_DATABASE_CONN_RETRY_DELAY:- 2}; done"]
    ports:
      - ${UMS_APP_PORT}:${UMS_APP_PORT}
    depends_on:
      - ums-production-database
    env_file:
      - .env
    networks:
      - production_network
    
volumes:
  ums_mysql_data_isolated:
    driver: local

networks:
  ums_production_network:
