version: "3.8"
services:
  oms-production-database:
    image: mysql_image:latest
    container_name: ${OMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${OMS_DATABASE_PORT}:${OMS_DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_TCP_PORT=${OMS_DATABASE_PORT}
      - MYSQL_ROOT_PASSWORD=${OMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${OMS_DATABASE_NAME}
      - MYSQL_USER=${OMS_DATABASE_USER}
      - MYSQL_PASSWORD=${OMS_DATABASE_PASSWORD}
    networks:
      - oms_production_network
    volumes:
      - oms_mysql_data_isolated:/var/lib/mysql
    
  oms-production-app:
    image: oms_prod_app:latest
    container_name: ${OMS_APP_CONTAINER_NAME}
    restart: no
    entrypoint: ["sh", "-c", "while ! npm run start:migrate:prod; do echo 'The database is not ready yet! Retrying after a delay...'; sleep ${OMS_DATABASE_CONN_RETRY_DELAY:- 2}; done"]
    ports:
      - ${OMS_APP_PORT}:${OMS_APP_PORT}
    depends_on:
      - oms-production-database
    env_file:
      - .env
    networks:
      - oms_production_network
    
volumes:
  oms_mysql_data_isolated:
    driver: local

networks:
  oms_production_network:
