version: "3.8"
services:
  test-database:
    image: mysql_image:latest
    container_name: ${OMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${OMS_DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${OMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${OMS_DATABASE_NAME}
      - MYSQL_USER=${OMS_DATABASE_USER}
      - MYSQL_PASSWORD=${OMS_DATABASE_PASSWORD}