version: "3.8"
services:
  migration-database:
    image: mysql_image:latest
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}