version: "3.8"
services:
  test-database:
    image: mysql_image:latest
    container_name: ${RMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${RMS_DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${RMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RMS_DATABASE_NAME}
      - MYSQL_USER=${RMS_DATABASE_USER}
      - MYSQL_PASSWORD=${RMS_DATABASE_PASSWORD}