version: "3.8"
services:
  rms-production-database:
    image: mysql_image:latest
    container_name: ${RMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${RMS_DATABASE_PORT}:${RMS_DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${RMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RMS_DATABASE_NAME}
      - MYSQL_USER=${RMS_DATABASE_USER}
      - MYSQL_PASSWORD=${RMS_DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${RMS_DATABASE_PORT}
    networks:
      - rms_production_network
    volumes:
      - rms_mysql_data_isolated:/var/lib/mysql
    
  rms-production-app:
    image: rms_prod_app:latest
    container_name: ${RMS_APP_CONTAINER_NAME}
    restart: no
    entrypoint: ["sh", "-c", "while ! npm run start:migrate:prod; do echo 'The database is not ready yet! Retrying after a delay...'; sleep ${RMS_DATABASE_CONN_RETRY_DELAY:- 2}; done"]
    ports:
      - ${RMS_APP_PORT}:${RMS_APP_PORT}
    depends_on:
      - rms-production-database
    env_file:
      - .env
    networks:
      - rms_production_network
    
volumes:
  rms_mysql_data_isolated:
    driver: local

networks:
  rms_production_network:
