version: "3.8"
services:
  dev-database:
    image: mysql_image:latest
    container_name: pms_dev_db
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - pms_development_network

  dev-app:
    image: pms_dev_app:latest
    container_name: pms_dev_app
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - dev-database
    env_file:
      - .env
    environment:
      NODE_ENV: development
    networks:
      - pms_development_network
    
networks:
  pms_development_network:
