version: "3.8"
services:
  migration-database:
    image: mysql_image:latest
    container_name: ${PMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${PMS_DATABASE_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PMS_DATABASE_NAME}
      - MYSQL_USER=${PMS_DATABASE_USER}
      - MYSQL_PASSWORD=${PMS_DATABASE_PASSWORD}