version: "3.8"
services:
  pms-production-database:
    image: mysql_image:latest
    container_name: ${PMS_DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${PMS_DATABASE_PORT}:${PMS_DATABASE_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PMS_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PMS_DATABASE_NAME}
      - MYSQL_USER=${PMS_DATABASE_USER}
      - MYSQL_PASSWORD=${PMS_DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${PMS_DATABASE_PORT}
    networks:
      - pms_production_network
    volumes:
      - pms_mysql_data_isolated:/var/lib/mysql
    
  pms-production-app:
    image: pms_prod_app:latest
    container_name: ${PMS_APP_CONTAINER_NAME}
    restart: no
    entrypoint: ["sh", "-c", "while ! npm run start:migrate:prod; do echo 'The database is not ready yet! Retrying after a delay...'; sleep ${PMS_DATABASE_CONN_RETRY_DELAY:- 2}; done"]
    ports:
      - ${PMS_APP_PORT}:${PMS_APP_PORT}
    depends_on:
      - pms-production-database
    env_file:
      - .env
    networks:
      - pms_production_network
    
volumes:
  pms_mysql_data_isolated:
    driver: local

networks:
  pms_production_network:
